// @ts-check

/**
 * One sidebar per lore track — autogenerated from each section's folder so
 * _category_.json drives nested, collapsible groups (expansion → era → entries).
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  aboutSidebar: [{type: 'autogenerated', dirName: '0-About'}],

  journeySidebar: [
    {type: 'autogenerated', dirName: '1-A-Realm-Reborn/1-The-Journey'},
  ],

  encyclopaediaSidebar: [
    {type: 'autogenerated', dirName: '1-A-Realm-Reborn/2-The-Encyclopaedia'},
  ],

  contextSidebar: [
    {type: 'autogenerated', dirName: '1-A-Realm-Reborn/3-Context'},
  ],
};

export default sidebars;
